apiVersion: v1
kind: Service
metadata:
  name: fbas
spec:
  ports:
    - name: http
      targetPort: 3000
      port: 3000
  selector:
    app: vac-benefits-directory
    task: fbas
  type: ClusterIP
status:
  loadBalancer: {}
