apiVersion: v1
kind: Service
metadata:
  name: find-benefits-and-services
spec:
  ports:
    - name: http
      targetPort: 3000
      port: 3000
  selector:
    app: vac-benefits-directory
    task: find-benefits-and-services
  type: ClusterIP
status:
  loadBalancer: {}
