steps:
  - name: node:10.8.0
    entrypoint: yarn
    args: ["install"]
  - name: node:10.8.0
    entrypoint: yarn
    args: ["jest", "-w", "8"]
  - name: node:10.8.0
    entrypoint: yarn
    args: ["lint"]
options:
  machineType: "N1_HIGHCPU_8"
