steps:
  - name: "gcr.io/cloud-builders/docker"
    id: build
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker build -t gcr.io/cds-snc/vac:$REVISION_ID --build-arg CIRCLE_SHA1=$$CIRCLE_SHA1 --build-arg AIRTABLE_READ_KEY=$$AIRTABLE_READ_KEY --build-arg GOOGLE_MAPS_KEY=$$GOOGLE_MAPS_KEY --build-arg GITHUB_PUBLIC_ACCESS_TOKEN=$$GITHUB_PUBLIC_ACCESS_TOKEN .",
      ]
    secretEnv:
      ["AIRTABLE_READ_KEY", "GITHUB_PUBLIC_ACCESS_TOKEN", "GOOGLE_MAPS_KEY"]
    env:
      - "CIRCLE_SHA1=$SHORT_SHA"
  - name: "gcr.io/cloud-builders/docker"
    id: push
    args: ["push", "gcr.io/cds-snc/vac:$REVISION_ID"]
  - name: "gcr.io/cds-snc/vac:$REVISION_ID"
    id: test
    entrypoint: /bin/sh
    args: ["-c", "cd /app && yarn jest"]
    waitFor:
      - push
  - name: "gcr.io/cds-snc/vac:$REVISION_ID"
    id: lint
    entrypoint: /bin/sh
    args: ["-c", "cd /app && yarn lint"]
    waitFor:
      - push
  - name: "gcr.io/cloud-builders/kubectl"
    id: deploy
    args:
      - "set"
      - "image"
      - "deployment/vac"
      - "vac=gcr.io/cds-snc/vac:$REVISION_ID"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=vac-cluster"

options:
  machineType: "N1_HIGHCPU_8"

secrets:
  - kmsKeyName: projects/cds-snc/locations/global/keyRings/cds-keys/cryptoKeys/vac
    secretEnv:
      AIRTABLE_READ_KEY: CiQADT94XiyVGg6MMf7ApdwnxawgfT+t16TfLq9cigVcTCkNmhoSOgAGcDO4M5ZGAkIRzbb0YVcgqt198Bj2hFOLuIcNPe86xOsMxTmedZSjkxp+n/Yo4T4/meOWx7/OulA=
      GITHUB_PUBLIC_ACCESS_TOKEN: CiQADT94XqB7WyNdJ7z6vBWFbUpR0hlRn/xZIX07ogl15CND/lQSUQAGcDO4rPdSfBsNZ+xTZMqEeE8Xj9ieh1FVYc+KfoVfp9us+2YQWaI5rO62fqNneaMcLNOixtOgYhfKlfd0SlpNHzkp5c6bldyxROv8+0W5ZA==
      GOOGLE_MAPS_KEY: CiQADT94XuUgykb73Gr/JZLueFh9xq7vcIckHZ/wnlQg5WwgsdgSUAAGcDO4f020FhpFGujfpiHBE8qZ/cRr9fJgNAiw8J5j3xuOP/zUMTTTYtWe7R4Y7DtcarjvWy/8lBbJ009vmOcAbilKHCJXcFiLP5tBJr8S
